const weatherCodes = {
    0: { description: "Clear sky", icon: "fa-sun" },
    1: { description: "Mainly clear", icon: "fa-cloud-sun" },
    2: { description: "Partly cloudy", icon: "fa-cloud" },
    3: { description: "Overcast", icon: "fa-cloud" },
    45: { description: "Fog", icon: "fa-smog" },
    48: { description: "Depositing rime fog", icon: "fa-smog" },
    51: { description: "Drizzle: Light intensity", icon: "fa-solid fa-cloud-rain" },
    53: { description: "Drizzle: Moderate intensity", icon: "fa-solid fa-cloud-rain" },
    55: { description: "Drizzle: Dense intensity", icon: "fa-solid fa-cloud-rain" },
    56: { description: "Freezing Drizzle: Light intensity", icon: "fa-snowflake" },
    57: { description: "Freezing Drizzle: Dense intensity", icon: "fa-snowflake" },
    61: { description: "Rain: Slight intensity", icon: "fa-cloud-showers-heavy" },
    63: { description: "Rain: Moderate intensity", icon: "fa-cloud-showers-heavy" },
    65: { description: "Rain: Heavy intensity", icon: "fa-cloud-showers-heavy" },
    66: { description: "Freezing Rain: Light intensity", icon: "fa-snowflake" },
    67: { description: "Freezing Rain: Heavy intensity", icon: "fa-snowflake" },
    71: { description: "Snow fall: Slight intensity", icon: "fa-snowflake" },
    73: { description: "Snow fall: Moderate intensity", icon: "fa-snowflake" },
    75: { description: "Snow fall: Heavy intensity", icon: "fa-snowflake" },
    77: { description: "Snow grains", icon: "fa-snowflake" },
    80: { description: "Rain showers: Slight", icon: "fa-cloud-showers-heavy" },
    81: { description: "Rain showers: Moderate", icon: "fa-cloud-showers-heavy" },
    82: { description: "Rain showers: Violent", icon: "fa-cloud-showers-heavy" },
    85: { description: "Snow showers: Slight", icon: "fa-snowflake" },
    86: { description: "Snow showers: Heavy", icon: "fa-snowflake" },
    95: { description: "Thunderstorm: Slight or moderate", icon: "fa-bolt" },
    96: { description: "Thunderstorm with slight hail", icon: "fa-bolt" },
    99: { description: "Thunderstorm with heavy hail", icon: "fa-bolt" },
  };
  
  export default weatherCodes;